name: On Push Tags Workflows

on:
  push:
    tags:
      - '*'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Generate Release From Tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  publish-npm:
    name: "Publish to NPM"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: NPM Install
        run: npm install
      - name: NPM Continous Integration
        run: npm ci
      - name: NPM Build
        run: npm run-script build
      - name: NPM Version of the Readme
        run: mv NPM-README.md README.md
      - name: NPM Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    name: "Publish to GitHub"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@open-template-hub'

      - name: NPM Install
        run: npm install
      - name: NPM Continous Integration
        run: npm ci
      - name: NPM Build
        run: npm run-script build
      - name: NPM Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  merge-from-master-to-develop:
    name: "Merge from master to develop"
    runs-on: ubuntu-latest
    needs: publish-npm

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}
          ref: develop
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}
          ref: master
          
      - name: Merge from master
        run: |
          git checkout develop
          git pull
          git config --global user.email "fatihturker35@gmail.com"
          git config --global user.name "Fatih Turker"
          git merge origin/master --allow-unrelated-histories
          npm i
          git push
