name: On Version Update Workflows

on:
  push:
    paths-ignore:
      - 'package.json'
    branches:
      - "master"

jobs:
  bump-version:
    name: "Update Version"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Bump Version and Create Tag
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

  merge-from-master-to-develop:
    name: "Merge from master to develop"
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

      - name: Merge from master
        run: |
          git pull
          git checkout develop
          git pull
          git reset --hard origin/master
          git merge master
          git push
