name: PR Open Workflows

on:
  pull_request:
    types: [ opened ]
    branches-ignore: [ 'workflow/dependency-update' ]

jobs:
  pr-labeler:
    name: 'Add Label to PR'
    runs-on: ubuntu-latest

    steps:
      - name: Add Label to PR
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

  automate-project-columns:
    name: 'Automate Project Columns'
    runs-on: ubuntu-latest

    steps:
      - name: Move PR to In-Progress
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Open Template Hub Servers
          column: In progress
          repo-token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

  milestone-binder:
    name: 'Milestone Binder'
    runs-on: ubuntu-latest

    steps:
      - name: Set Milestone of the PR
        uses: Code-Hex/auto-milestone-binder@v1.0.1
        with:
          github-token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

  cron-dependency-checker:
    name: 'Cron Dependency Checker'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: NPM Install
        run: npm i
      - name: Npm Outdated
        run: npm run outdated
      - name: Build
        run: npm run build

      - name: Check for Changes
        run: |
          if git diff --exit-code; then
            echo "::set-env name=changes_exist::false"
          else
            echo "::set-env name=changes_exist::true"
          fi

      - name: Git Commit and Push
        if: ${{ env.changes_exist == 'true' }}
        run: |
          git config --global user.email "98660390+oth-service-user@users.noreply.github.com"
          git config --global user.name "OTH Service User"
          git commit -am "Workflow/dependency check"
          git push
